# Generated by Django 6.0.1 on 2026-01-20 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MisuratoreEventiWide',
            fields=[
                ('device_id', models.TextField()),
                ('ts_s', models.BigIntegerField()),
                ('instant_flow_rate_2', models.FloatField(null=True)),
                ('instant_flow_rate_1', models.FloatField(null=True)),
                ('fluid_velocity_2', models.FloatField(null=True)),
                ('fluid_velocity_1', models.FloatField(null=True)),
                ('instant_heat_flow_rate', models.FloatField(null=True)),
                ('instant_heat_flow_rate_1', models.FloatField(null=True)),
                ('return_water_temperature_2', models.FloatField(null=True)),
                ('return_water_temperature_1', models.FloatField(null=True)),
                ('supplying_water_temperature', models.FloatField(null=True)),
                ('supplying_water_temperature_1', models.FloatField(null=True)),
                ('pk', models.CompositePrimaryKey('device_id', 'ts_s', blank=True, editable=False, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'mv_misuratore_trebisacce_eventi_wide',
                'managed': False,
            },
        ),
    ]
