# Generated by Django 5.2.8 on 2026-01-21 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portale', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tab_measurements',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('device_id', models.TextField()),
                ('ts_s', models.DateTimeField()),
                ('instant_flow_rate_2', models.FloatField(null=True)),
                ('instant_flow_rate_1', models.FloatField(null=True)),
                ('fluid_velocity_2', models.FloatField(null=True)),
                ('fluid_velocity_1', models.FloatField(null=True)),
                ('instant_heat_flow_rate_2', models.FloatField(null=True)),
                ('instant_heat_flow_rate_1', models.FloatField(null=True)),
                ('return_water_temperature_2', models.FloatField(null=True)),
                ('return_water_temperature_1', models.FloatField(null=True)),
                ('supplying_water_temperature_2', models.FloatField(null=True)),
                ('supplying_water_temperature_1', models.FloatField(null=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'tab_measurements',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='tab_measurements_clean',
            fields=[
                ('id_misuratore', models.TextField()),
                ('data_misurazione', models.DateTimeField()),
                ('flow_ls', models.FloatField()),
                ('is_likely', models.BooleanField()),
                ('thr_low', models.FloatField(null=True)),
                ('thr_high', models.FloatField(null=True)),
                ('pk', models.CompositePrimaryKey('id_misuratore', 'data_misurazione', blank=True, editable=False, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'tab_measurements_clean',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='tab_misuratori',
            fields=[
                ('id_misuratore', models.TextField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255, null=True)),
                ('latitude', models.FloatField(null=True)),
                ('longitude', models.FloatField(null=True)),
                ('created_at', models.DateTimeField()),
                ('is_active', models.BooleanField()),
            ],
            options={
                'db_table': 'tab_misuratori',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='tab_statistiche_misuratori',
            fields=[
                ('id_misuratore', models.TextField(primary_key=True, serialize=False)),
                ('total_measurements', models.BigIntegerField()),
                ('first_measurement', models.DateTimeField(null=True)),
                ('last_measurement', models.DateTimeField(null=True)),
                ('avg_24h', models.FloatField(null=True)),
                ('avg_7d', models.FloatField(null=True)),
                ('avg_30d', models.FloatField(null=True)),
                ('avg_360d', models.FloatField(null=True)),
                ('avg_all_time', models.FloatField(null=True)),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'tab_statistiche_misuratori',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='MisuratoreEventiWide',
        ),
    ]
