# Generated by Django 6.0.1 on 2026-01-23 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portale', '0002_tab_measurements_tab_measurements_clean_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tab_measurements',
            options={'managed': False, 'verbose_name_plural': 'Tab measurements'},
        ),
        migrations.AlterModelOptions(
            name='tab_measurements_clean',
            options={'managed': False, 'verbose_name_plural': 'Tab measurements clean'},
        ),
        migrations.AlterModelOptions(
            name='tab_misuratori',
            options={'managed': False, 'verbose_name_plural': 'Tab misuratori'},
        ),
        migrations.AlterModelOptions(
            name='tab_statistiche_misuratori',
            options={'managed': False, 'verbose_name_plural': 'Tab statistiche misuratori'},
        ),
        migrations.AlterModelTable(
            name='tab_statistiche_misuratori',
            table='mv_statistiche_misuratori',
        ),
    ]
