# Generated by Django 6.0.1 on 2026-02-05 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portale', '0003_alter_tab_measurements_options_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='tab_statistiche_misuratori',
            table='tab_statistiche_misuratori',
        ),
    ]
